Setting:
  gpu: '0'
  seed: 2020
  workers: 8  # data loader workers

DATA:
  train_root: /home/cyyan/projects/MToPrior/data/mt2patch/train.txt
  val_root: /home/cyyan/projects/MToPrior/data/mt2patch/test.txt
  seg_classes: 2
  cls_classes: 2

MODEL:
  arch: psp
  layers: 50
  sync_bn: False  # adopt sync_bn or not
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
#  aux_weight: 0.4
  start_epoch: 0
  index_split: 5

OPTIM:
  batch_size: 16  # batch size for training
  epochs: 200
  base_lr: 0.001
  lr_step: 10
  power: 0.9
  momentum: 0.9
  decay: 0.0001

TRAIN:
  HyValidation: False
  branch_S: True
  SegTo: False
  seg_weight: 1
  save_path: /home/cyyan/projects/MToPrior/models/
  weight: #/home/cyyan/projects/CaSoGP/model_Para/epoch_92.pth
  resume:  # path to latest checkpoint (default: none)

TEST:
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  model_path:
