DATA:
  train_root: /home/cyyan/projects/CaSoGP/data/train6.txt
  val_root: /home/cyyan/projects/CaSoGP/data/test.txt
  seg_classes: 2
  cls_classes: 2

TRAIN:
  lr_step: 10
  HyValidation: False
  branch_S: True
  SegTo: False
  seg_weight: 1
  batch_size: 16  # batch size for training
  base_lr: 0.001
  epochs: 100
  save_path: /home/cyyan/projects/CaSoGP/model_singleSEG/
  weight: #/home/cyyan/projects/CaSoGP/model_Para/epoch_92.pth
  resume:  # path to latest checkpoint (default: none)


  index_split: 5
  arch: psp
  layers: 50
  sync_bn: False  # adopt sync_bn or not
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
#  aux_weight: 0.4
  workers: 4  # data loader workers
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:


TEST:
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
#  model_path: ../model_justClass/epoch_35.pth  # evaluation model path
#  model_path: ../model_Validation/epoch_47.pth  # evaluation model path
#  model_path: ../model_ValidationFeature/epoch_39.pth  # evaluation model path
#  model_path: ../model_Parallel/epoch_92.pth  # evaluation model path
#  model_path: ../model_Prob/epoch_84.pth  # evaluation model path
  model_path: /home/cyyan/projects/CaSoGP/model_singleSEG/epoch_100.pth
